apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-variaveis-ambiente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-variaveis-ambiente
  template:
    metadata:
      labels:
        app: app-variaveis-ambiente
    spec:
      containers:
        - name: app-variaveis-ambiente
          image: pauloaragaodev/app-variaveis-ambiente:v1
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: app-variaveis-ambiente
spec:
  selector:
    app: app-variaveis-ambiente
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000